# file      : tests/basic/buildfile
# copyright : Copyright (c) 2016-2019 Code Synthesis Ltd
# license   : ISC; see accompanying COPYING file

import libs = libpkgconf%lib{pkgconf}

exe{driver}: {h c}{*} $libs testscript
